id: ICBDC8D9D
ocr_import_info:
  timestamp: '2023-09-25T08:20:41.184893+00:00'
  batch_id: batch-cff0
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-25 09:15:45.117441+00:00
last_modified: 2023-09-25 09:15:45.117448+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W2KG210276
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2KG210276
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རྩ་བའི་ཤེས་རབ་ཀྱི་དོན་བསྡུ་སོགས།
  languages:
  - bo
  author: གུང་རུ་རྒྱལ་མཚན་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9076351913098951
  ocr_word_median_confidence_index: 0.96535474
bases:
  I3CN22231:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN22231
      total_pages: 750
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN22231.txt
    statistics:
      ocr_word_median_confidence_index: 0.96535474
      ocr_word_mean_confidence_index: 0.9076351913098951
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
